### ISSUE TITLE
test typescript code error

### ISSUE THREAD

**Issue by Curlbotter** [Qeenon/Amadeus#16]
Amadeus git:(mawa) ✗ node node_modules/ts-node/dist/bin.js .\js\w3g_parse.ts .\LastReplay.w3g > gg.out
Error: Cannot find module '/home/navi/Amadeus/.jsw3g_parse.ts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/home/lain/Amadeus/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/home/lain/Amadeus/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

**Comment by Qeenon** [comment]
on linux you should replace `\` with `/` corrected readme

**Comment by Qeenon** [comment]
@Curlbotter please let me know if you still have issues, closing for now.
